# Generated by Django 6.0.1 on 2026-01-18 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('chor', 'Chor'), ('police', 'Police'), ('citizen', 'Citizen')], max_length=10)),
                ('is_alive', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('lobby', 'Lobby'), ('reveal', 'Role Reveal'), ('discussion', 'Discussion'), ('police_turn', 'Police Turn'), ('result', 'Result')], default='lobby', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=10)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
    ]
