# Generated by Django 6.0.1 on 2026-01-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('chor', 'Chor'), ('police', 'Police'), ('citizen', 'Citizen')], max_length=10),
        ),
    ]
