# Generated by Django 4.2.11 on 2026-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamestate_id_alter_player_id_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('chor', 'Chor'), ('police', 'Police'), ('citizen', 'Citizen')], max_length=10, null=True),
        ),
    ]
